### ISSUE TITLE
TODO for improvements and finalisation 

### ISSUE THREAD

**Issue by evezeyl** [NorwegianVeterinaryInstitute/diplotopia#1]
TODO 
---
- [ ] reread purge haplotigs and explain better 
- [ ] read more about the variant normalisation  
- [ ] more nextflow training ... need to improve / groovy

---- 
Pipeline  itself 

- [ ] include the version notes ...  check version output and add if missing 
  - [ ]  debug - R.version is empty  - quarto R script for filtering contigs-> sessionInfo not working on qmd ? or sink ? find a way to get it. -> see eg https://stackoverflow.com/questions/39131017/sink-wont-print-output-to-text-file-in-rmarkdown (tried {sink ..} but did not work
- [ ] modules config - selection output
- [ ]  include R packages - script ? session info 
- [ ]  adjust the system configs (now I have modified the saga.config) for other institutions can use / adjust the pipeline fast (but not urgent yet)
  - [ ] base.config 
  - [ ] hpc.config

Documentation 
- [x] track description visual (until now) 
  - [x] FILTER_CONTIGS
  - [x] COMPASS
  - [x] HAPLOPURGE
  - [x]  VARWRRUM:

- [x] 1_Pipeline_description.mdshort description tracks, purpose and references
  - [x] FILTER_CONTIGS
  - [x] COMPASS
  - [x] HAPLOPURGE
  - [x]  VARWRRUM:

--------------
- [x] 2_Installation.md
- [x] SAGA_USERS_instructions.md
- [ ] 3_How_to_Run.md
--------------
Details tracks choices   - need review - improvements 
- [ ] 4_Choices.md
  - [ ] Filtering_contigs.md
  - [ ] Haplopurge_choices.md
  - [ ] VARWRRUM_choices.md 

-------------
Description of output and options 

Then send to review - colleagues 
TRACKING : 
Thomas : review 
- [x] 1_Pipeline_description.md
- [ ] 2_Installation.md
- [ ] SAGA_USERS_instructions.md
- [ ] 3_How_to_Run.md
- [ ] 4_Choices.md
  - [ ] Filtering_contigs.md
  - [ ] Haplopurge_choices.md
  - [ ] VARWRRUM_choices.md
